name: GitHub Actions CI pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions CI
on: [push]
jobs:
  CI_pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI pipeline."
      - name: Setting up the enviroment
        run: |
          sudo apt install pip
          sudo apt update 
          sudo apt upgrade -y python3-dev
          mkdir pintuplomer

      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          path: pintuplomer

      - name: installing depences 
        run: |
          cd pintuplomer
          python3 -m venv .venv
          . .venv/bin/activate
         
          python3 -m pip install --upgrade pip

          pip install -r requirements.txt
          pip install pytest 
          pip install testcontainers

      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Testing
        env: 
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_EXTENSIONS: ${{ secrets.ALLOWED_EXTENSIONS }}
          KEY: ${{ secrets.KEY }}
        run: |
          echo "Running pytest"
          cd pintuplomer
          PYTHONPATH=.  ./.venv/bin/pytest 

      - run: echo "This job's status is ${{ job.status }}."
